apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: dendrite-vault-backend
  namespace: platform
spec:
  provider:
    vault:
      server: "http://vault.platform.svc.cluster.local:8200"
      path: "dendrite"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "vault-kubernetes"
