apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: vault-example
  namespace: platform
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: humble-init-secrets
  data:
  - secretKey: ak_admin_password
    remoteRef:
      key: init
      property: ak_admin_password
  - secretKey: ak_admin_token
    remoteRef:
      key: init
      property: ak_admin_token
  - secretKey: ak_gitea_oauth2_client_id
    remoteRef:
      key: init
      property: ak_gitea_oauth2_client_id
  - secretKey: ak_gitea_oauth2_client_secret
    remoteRef:
      key: init
      property: ak_gitea_oauth2_client_secret
