apiVersion: locmai.dev/v1alpha1
kind: SecretGenerator
metadata:
  name: saleor-secrets
  namespace: default
spec:
  name: saleor-secrets
  secrets:
  - name: SECRET_KEY
    length: 32
  - name: postgresql-password
    length: 24
  - name: REDIS_PASSWORD
    length: 24
  backend: "kubernetes"
