- name: Create Kubernetes cluster
  hosts: metal
  roles:
    - k3s
    - automatic_upgrade

- name: Install Cilium
  hosts: localhost
  roles:
    - cilium

- name: Create some basic config
  hosts: localhost
  roles:
    - metallb_config
