- name: Install/Upgrade Cilium
  block:
  - name: Install Cilium
    ansible.builtin.command: >
      cilium install --helm-set prometheus.enabled=true 
      --helm-set operator.prometheus.enabled=true 
      --helm-set hubble.enabled=true 
      --helm-set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,http}" 
      --helm-set hubble.ui.enabled=true 
      --helm-set hubble.relay.enabled=true
  rescue:
  - name: Upgrade Cilium
    ansible.builtin.command: cilium upgrade
- name: Enable Hubble
  ansible.builtin.command: cilium hubble enable --ui
  ignore_errors: true
- name: Wait for Cilium installation
  ansible.builtin.command: cilium status --wait
