{{- if .Values.alvisio.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-alvisio
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  destination:
    name: in-cluster
    namespace: {{ .Values.argocd.project }}
  source:
    path: kubernetes/deployments
    repoURL: git@github.com:alvisio-io/alvisio-ops.git
    targetRevision: main
    helm:
      releaseName: alvisio
      values: |
        dummy: data
{{- end }}
