{{- if .Values.consul.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-consul
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  # syncPolicy:
  #   automated:
  #     selfHeal: true
  #     prune: true
  destination:
    name: in-cluster
    namespace: {{ .Values.argocd.project }}
  source:
    chart: consul
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.41.1
    helm:
      releaseName: consul
      values: |
        server:
          replicas: 5
        ingress:
          enabled: false
          # Optionally set the ingressClassName.
          ingressClassName: ""
{{- end }}
