{{- if .Values.consul.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-consul
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  # syncPolicy:
  #   automated:
  #     selfHeal: true
  #     prune: true
  destination:
    name: in-cluster
    namespace: {{ .Values.argocd.project }}
  source:
    chart: consul
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.44.0
    helm:
      releaseName: consul
      values: |
        global:
          # The default log level to apply to all components which do not otherwise override this setting.
          # It is recommended to generally not set this below "info" unless actively debugging due to logging verbosity.
          # One of "debug", "info", "warn", or "error".
          # @type: string
          logLevel: "debug"
        server:
          replicas: 3
          affinity: ""
          topologySpreadConstraints: |
            - maxSkew: 1
              topologyKey: topology.kubernetes.io/zone
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                matchLabels:
                  app: consul
                  release: consul
                  component: server
        ingress:
          enabled: false
          # Optionally set the ingressClassName.
          ingressClassName: ""
{{- end }}
