{{- if and .Values.cortex.enabled .Values.cortex.basicAuth.insecure }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cortex.basicAuth.secretName }}
stringData:
  .htpasswd: |
    humble:$apr1$c2oq76fk$M6sAHf72.8WZmgv0/Oa8I0
{{- end }}
