{{- if .Values.filebrowser.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-filebrowser
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  destination:
    name: in-cluster
    namespace: {{ .Values.argocd.project }}
  source:
    chart: filebrowser
    repoURL: https://locmai.github.io/charts/
    targetRevision: 0.0.2
    helm:
      releaseName: filebrowser
      values: |
        ingress:
          enabled: false
{{- end }}
