{{- if .Values.matrixalertmanager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-matrixalertmanager
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  destination:
    name: in-cluster
    namespace: {{ .Values.argocd.project }}
  source:
    chart: matrixalertmanager
    repoURL: https://locmai.github.io/charts/
    targetRevision: 0.0.1
    helm:
      releaseName: matrixalertmanager
      values: |
        config:
          default:
            base_url: "https://dendrite.{{ .Values.global.domain }}"
            server_name: "maibaloc.com"

            theme: "light"
{{- end }}
