{{- if .Values.yutaops.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-yutaops
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  # syncPolicy:
  #   automated:
  #     selfHeal: true
  #     prune: true
  destination:
    name: in-cluster
    namespace: {{ .Values.argocd.project }}
  source:
    chart: yuta
    repoURL: https://locmai.github.io/charts/
    targetRevision: 0.0.2
    helm:
      releaseName: yutaops
      values: |
        core:
          enabled: false
        messaging:
          enabled: false
        webhook:
          enabled: true
        nats:
          enabled: true
{{- end }}
