{{- if .Values.sonarqube.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-sonarqube
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.sonarqube.namespace }}
  source:
    chart: sonarqube
    repoURL: https://SonarSource.github.io/helm-chart-sonarqube
    targetRevision: master
    helm:
      releaseName: sonarqube
      values: |
        postgresql:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              additionalLabels:
                layer: platform
          persistence:
            enabled: true
            storageClass: longhorn-default
{{- end }}