kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbench-pv-claim-nfs
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dbench-nfs
spec:
  template:
    spec:
      containers:
      - name: dbench
        image: zayashv/dbench:latest
        imagePullPolicy: Always
        env:
          - name: DBENCH_MOUNTPOINT
            value: /data
          # - name: DBENCH_QUICK
          #   value: "yes"
        volumeMounts:
        - name: dbench-pv-nfs
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: dbench-pv-nfs
        persistentVolumeClaim:
          claimName: dbench-pv-claim-nfs
  backoffLimit: 4
