argocd:
  namespace: argocd
  project: platform
  targetRevision: main

global:
  domain: "placeholder.com"

# Secret management
vault:
  enabled: true
  installOperator: true
  ingress:
    enabled: true
  namespace: platform
  initSecrets: false
  storageClass: "longhorn"

externalSecrets:
  enabled: true
  namespace: platform

secretGenerator:
  enabled: true
  namespace: platform
  targetRevision: master

etcd:
  enabled: false
  namespace: platform

argo_workflow:
  enabled: false
  namespace: argoworkflow

argo_events:
  enabled: false
  namespace: argoworkflow

minio:
  enabled: false
  installOperator: false
