argocd:
  namespace: argocd
  project: platform
  targetRevision: main

global:
  domain: "placeholder.com"

# Secret managment
vault:
  enabled: false

# Workflow engines
tekton:
  enabled: true
  namespace: platform

etcd:
  enabled: false
  namespace: platform

argo_workflow:
  enabled: false
  namespace: kube-system

# IAM
authentik:
  enabled: true
  namespace: platform

# SCM
gitea:
  enabled: true
  namespace: platform
  ingress:
    enabled: true
