argocd:
  namespace: argocd
  project: platform
  targetRevision: main

# Kube Prometheus + Grafana stack 
monitoring:
    enabled: false
    namespace: monitoring

loki:
    enabled: true
    namespace: monitoring

