apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: vault-config-tool
  namespace: platform
spec:
  schedule: '0 23 * * *'
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: configure-vault
    serviceAccountName: init-tools
    templates:
    - name: configure-vault
      container:
        image: locmai/humble-vault-config-tool:0.0.1
        command: [/vault-init-tool]
        env:
        - name: HUMBLE_DOMAIN
          value: "{{ .Values.global.domain }}"
