apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pipelines
  namespace: argocd
spec:
  description: ''
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - git@github.com:locmai/**
  - https://github.com/locmai/**
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: pipelines
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/syncPolicy/automated
  destination:
    name: in-cluster
    namespace: pipelines
  source:
    path: 'platform/pipelines/templates'
    repoURL: git@github.com:locmai/humble.git
    targetRevision: main
    plugin:
      name: argocd-vault-plugin
      env:
        - name: helm_args
          value: -f values.yaml
        - name: VAULT_ADDR
          value: https://vault-ui.vault.svc.cluster.local
        - name: AVP_TYPE
          value: vault
        - name: AVP_AUTH_TYPE
          value: k8s
        - name: AVP_K8S_ROLE
          value: argocd-server