# Storage
longhorn:
  enabled: false

# Observability
monitoring:
  enabled: true

tracing:
  enabled: false

logging:
  enabled: false

dashboard:
  enabled: false

opentelemetry:
  enabled: false

# Ingress / Load balancer
metallb:
  enabled: false

ingress_nginx:
  enabled: true

certmanager:
  enabled: false

istio:
  enabled: false

# System maintainers/cleaners
descheduler:
  enabled: false

systemUpgrade:
  enabled: false

kured:
  enabled: false
