# Storage
longhorn:
  enabled: true

# Observability
monitoring:
  enabled: true

tracing:
  enabled: false

logging:
  enabled: true

dashboard:
  enabled: true

# Ingress / Load balancer
metallb:
  enabled: true

ingress_nginx:
  enabled: true

certmanager:
  enabled: true

