# Default
argocd:
 project: system
 namespace: argocd

global:
  domain: "placeholder.com"

# Storage
longhorn:
  enabled: true
  namespace: longhorn-system

# Observability
mimir:
  enabled: false
  namespace: observability

monitoring:
  enabled: true
  namespace: observability
  remoteWrite:
    enabled: false

tracing:
  enabled: false
  namespace: observability

logging:
  enabled: true
  namespace: observability

dashboard:
  enabled: true
  namespace: observability
  targetRevision: main

oncall:
  enabled: false

opentelemetry:
  enabled: true
  namespace: observability
  logLevel: info
  # TODO Add config.yaml here for templating
  # config:
  # ...
  # TODO Add Jaeger configuration

# Ingress / Load balancer
metallb:
  enabled: true
  namespace: metallb-system

ingress_nginx:
  enabled: true

certmanager:
  enabled: true
  namespace: cert-manager
