# Storage
longhorn:
  enabled: true

# Observability
mimir:
  enabled: false

monitoring:
  enabled: true

tracing:
  enabled: true

logging:
  enabled: true

dashboard:
  enabled: true

oncall:
  enabled: true

# Ingress / Load balancer
metallb:
  enabled: true

ingress_nginx:
  enabled: true

certmanager:
  enabled: true
