# Default
argocd:
 project: system
 namespace: argocd

global:
  domain: "placeholder.com"

# Storage
longhorn:
  enabled: true
  namespace: longhorn-system

# Observability
monitoring:
  enabled: true
  namespace: observability

tracing:
  enabled: true
  namespace: observability

logging:
  enabled: true
  namespace: observability

dashboard:
  enabled: true
  namespace: observability
  targetRevision: main

opentelemetry:
  enabled: true
  namespace: observability
  logLevel: info
  # TODO Add config.yaml here for templating
  # config:
  # ...
  # TODO Add Jaeger configuration

# Ingress / Load balancer
metallb:
  enabled: true
  namespace: metallb-system

ingress_nginx:
  enabled: true

certmanager:
  enabled: true
  namespace: cert-manager

istio:
  enabled: true
  namespace: istio-system
  gateway:
    enabled: false

# System maintainers/cleaners
descheduler:
  enabled: true
  namespace: descheduler

systemUpgrade:
  enabled: true

kured:
  enabled: true
