argocd:
 project: system
 namespace: argocd

longhorn:
  enabled: true
  namespace: longhorn-system

ingress_nginx:
  enabled: true

monitoring:
  enabled: true
  namespace: observability

loki:
  enabled: true
  namespace: observability

metallb:
  enabled: true
  namespace: metallb-system