# Default
argocd:
 project: system
 namespace: argocd

# Storage
longhorn:
  enabled: true
  namespace: longhorn-system

# Observability
monitoring:
  enabled: true
  namespace: observability

loki:
  enabled: true
  namespace: observability

dashboard:
  enabled: true
  namespace: observability
  targetRevision: main

# Ingress / Load balancer
metallb:
  enabled: true
  namespace: metallb-system

ingress_nginx:
  enabled: true

certmanager:
  enabled: true
  namespace: cert-manager
  issuer:
    enabled: false
    email: locmai0201@gmail.com