# RBAC for Argo Workflow SSO configuration
{{- if .Values.argo_workflow.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-default-login
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: engineer-user
  annotations:
    workflows.argoproj.io/rbac-rule: "'engineer' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: engineer-role
subjects:
  - kind: ServiceAccount
    name: admin-user
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  annotations:
    workflows.argoproj.io/rbac-rule: "'admin' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: engineer-role
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
      - workflows
      - cronworkflows
      - workflowtemplates
      - clusterworkflowtemplates
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: engineer-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: engineer-role
subjects:
  - kind: ServiceAccount
    name: engineer-user
{{- end }}
