{{- if .Values.argo_workflow.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-argo-workflow
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.argo_workflow.namespace }}
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.16.7
    helm:
      releaseName: argo-workflows
      values: |
        server:
          extraArgs:
            - --auth-mode=sso
            - --auth-mode=client
          sso:
            issuer: "https://auth.maibaloc.com/v1/identity/oidc/provider/vault-provider"
            sessionExpiry: 240h
            clientId:
              name: humble-oidc-secrets
              key: OIDC_CLIENT_ID
            clientSecret:
              name: humble-oidc-secrets
              key: OIDC_CLIENT_SECRET
            redirectUrl: https://workflows.{{ .Values.global.domain }}/oauth2/callback
            rbac:
              enabled: true
            scopes:
              - groups
              - openid
              - user
              - email
            userInfoPath: /v1/identity/oidc/provider/vault-provider/userinfo
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              external-dns.alpha.kubernetes.io/target: "{{ .Values.global.env }}-humble-tunnel.{{ .Values.global.domain }}"
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
            ingressClassName: "nginx"
            hosts:
              - &host "workflows.{{ .Values.global.domain }}"
            paths:
              - /
            pathType: Prefix
            tls:
              - secretName: workflows-tls-certificate
                hosts:
                  - *host
        controller:
          workflowNamespaces: ["default", "kube-system"]	
{{- end }}
