{{- if .Values.authentik.enabled }}
apiVersion: v1
data:
  ak_admin_token: {{ include "common.secrets.passwords.manage" (dict "secret" "authentik-aka-secret" "key" "ak_admin_token" "providedValues" (list "authentik.secretValue") "length" 64 "context" $) }}
  ak_admin_password: {{ include "common.secrets.passwords.manage" (dict "secret" "authentik-aka-secret" "key" "ak_admin_password" "providedValues" (list "authentik.secretValue") "length" 32 "context" $) }}
  ak_gitea_oauth2_client_id: {{ include "common.secrets.passwords.manage" (dict "secret" "authentik-aka-secret" "key" "ak_gitea_oauth2_client_id" "providedValues" (list "authentik.secretValue") "length" 40 "strong" false "context" $) }}
  ak_gitea_oauth2_client_secret: {{ include "common.secrets.passwords.manage" (dict "secret" "authentik-aka-secret" "key" "ak_gitea_oauth2_client_secret" "providedValues" (list "authentik.secretValue") "length" 128 "strong" false "context" $) }}
kind: Secret
metadata:
  name: authentik-aka-secret
{{- end }}