{{- if .Values.authentik.enabled }}
apiVersion: v1
data:
  authentik_aka_token: {{ include "common.secrets.passwords.manage" (dict "secret" "authentik-aka-token" "key" "authentik_aka_token" "providedValues" (list "authentik.secretValue") "length" 64 "context" $) }}
kind: Secret
metadata:
  name: authentik-aka-token
{{- end }}
