{{- if .Values.authentik.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-authentik
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.authentik.namespace }}
  source:
    chart: authentik
    repoURL: https://charts.goauthentik.io
    targetRevision: 4.0.3
    helm:
      releaseName: authentik
      values: |
        authentik:
          secret_key: "PleaseGenerateA50CharKey"
          # This sends anonymous usage-data, stack traces on errors and
          # performance data to sentry.beryju.org, and is fully opt-in
          error_reporting:
          enabled: true
          postgresql:
            password: "ThisIsNotASecurePassword"
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            external-dns.alpha.kubernetes.io/exclude: 'true'
          hosts:
            - host: authentik.maibaloc.com
              paths:
                - path: "/"
                  pathType: Prefix
          tls:
            - hosts:
              - authentik.maibaloc.com

        postgresql:
         enabled: true
         postgresqlPassword: "ThisIsNotASecurePassword"
        redis:
          enabled: true
{{- end }}
