{{- if .Values.authentik.enabled }}
apiVersion: v1
data:
  ak_admin_token: {{ include "common.secrets.passwords.manage" (dict "secret" "authentik-aka-secret" "key" "ak_admin_token" "providedValues" (list "authentik.secretValue") "length" 64 "context" $) }}
  ak_admin_password: {{ include "common.secrets.passwords.manage" (dict "secret" "authentik-aka-secret" "key" "ak_admin_password" "providedValues" (list "authentik.secretValue") "length" 32 "context" $) }}
kind: Secret
metadata:
  name: authentik-aka-secret
{{- end }}
