{{- if .Values.externalSecrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-external-secrets
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.externalSecrets.namespace }}
  source:
    chart: kubernetes-external-secrets
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 8.5.1
    helm:
      releaseName: external-secrets
      values: |
        env:
          POLLER_INTERVAL_MILLISECONDS: 10000
          WATCH_TIMEOUT: 60000
          WATCHED_NAMESPACES: ""  # Comma separated list of namespaces, empty or unset means ALL namespaces.
          LOG_LEVEL: info
          LOG_MESSAGE_KEY: "msg"

          METRICS_PORT: 3001
          VAULT_ADDR: http://vault.platform.svc.cluster.local:8200/
          DEFAULT_VAULT_MOUNT_POINT: "kubernetes"
          DEFAULT_VAULT_ROLE: "vault-kubernetes"
{{- end }}
