{{- if .Values.gitea.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-gitea
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.gitea.namespace }}
  source:
    chart: gitea
    repoURL: https://dl.gitea.io/charts/
    targetRevision: 4.1.1
    helm:
      releaseName: gitea
      values: |
        ingress:
          enabled: false
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            external-dns.alpha.kubernetes.io/target: "humble-tunnel.{{ .Values.global.domain }}"
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          hosts:
            - host: &host git.{{ .Values.global.domain }}
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: gitea-tls-certificate
              hosts:
                - *host
        gitea:
          config:
            server:
              LANDING_PAGE: explore
          # Either specify inline `key` and `secret` or refer to them via `existingSecret`
          oauth:
            - name: 'authentik'
              provider: 'OpenID Connect'
              existingSecret: gitea-oauth2-secrets
              autoDiscoverUrl: "https://{{ .Values.global.domain }}/application/o/gitea/.well-known/openid-configuration"
{{- end }}
