---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: init-tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: platform
  name: init-tools
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: init-tools
  namespace: platform
subjects:
- kind: ServiceAccount
  name: init-tools
  namespace: platform
roleRef:
  kind: Role
  name: init-tools
  apiGroup: rbac.authorization.k8s.io
