{{- if and .Values.vault.namespace .Values.externalSecrets.namespace -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-init-sercrets
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.externalSecrets.namespace }}
  source:
    path: platform/secrets
    repoURL: https://github.com/locmai/humble.git
    targetRevision: main
{{- end }}
