{{- if .Values.openldap.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-openldap
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.openldap.namespace }}
  source:
    chart: openldap-stack-ha
    repoURL: https://jp-gouin.github.io/helm-openldap/
    targetRevision: 2.1.6
    helm:
      releaseName: openldap
      values: |
        ltb-passwd:
          enabled: false

        phpldapadmin:
          enabled: true
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              external-dns.alpha.kubernetes.io/target: "humble-tunnel.maibaloc.com"
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
            path: /
            ## Ingress Host
            hosts:
            - &host ldapadmin.maibaloc.com
            tls:
            - secretName: phpldapadmin-tls-secret
              hosts:
              - *host
          env:
            PHPLDAPADMIN_LDAP_HOSTS: openldap-openldap-stack-ha
{{- end }}
