{{- if .Values.tekton.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
  annotations:
    hajimari.io/enable: "true"
    hajimari.io/appName: "Tekton"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: &host tekton.{{ .Values.global.domain }}
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: tekton-dashboard
            port:
              name: http
  tls:
  - hosts:
    - *host
    secretName: tekton-tls-certificate
{{- end }}
