{{- if .Values.temporal.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-temporal
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: platform 
  source:
    chart: temporal
    repoURL: https://locmai.github.io/charts/ 
    targetRevision: 0.32.0
    helm:
      releaseName: temporal 
      values: |
        server:
          replicaCount: 1
        cassandra:
          config:
            cluster_size: 1
        prometheus:
          enabled: false
        grafana:
          enabled: false
        elasticsearch:
          enabled: false
{{- end }}
