{{- if .Values.temporal.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-temporal
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: platform
  source:
    chart: temporal
    repoURL: https://locmai.github.io/charts/
    targetRevision: 0.32.0
    helm:
      releaseName: temporal
      values: |
        server:
          replicaCount: 1
          config:
            persistence:
              default:
                driver: "cassandra"
                cassandra:
                  hosts: ["cassandra"]
                  port: 9042
                  keyspace: temporal
                  user: "cassandra"
                  existingSecret: "temporal-cassandra"
                  secretKey: "temporal-cassandra"
              visibility:
                driver: "cassandra"
                cassandra:
                  hosts: ["cassandra"]
                  port: 9042
                  keyspace: temporal_visibility
                  user: "cassandra"
                  existingSecret: "temporal-cassandra"
                  secretKey: "temporal-cassandra"
        web:
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            hosts:
              - &host "temporal.{{ .Values.global.domain }}"
            tls:
              - secretName: temporal-tls
                hosts:
                  - *host
        schema:
          setup:
            enabled: true
            backoffLimit: 100
          update:
            enabled: true
            backoffLimit: 100
        cassandra:
          enabled: false
        prometheus:
          enabled: false
        grafana:
          enabled: false
        elasticsearch:
          enabled: false
{{- end }}
