{{- if .Values.vault.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-vault
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.vault.namespace }}
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.18.0
    helm:
      releaseName: vault
      values: |
        server:
          dev:
            enabled: false
          ingress:
            enabled: false
            ingressClassName: nginx
            annotations:
              hajimari.io/enable: "true"
              hajimari.io/appName: "vault"
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: &host vault.{{ .Values.global.domain }}
                paths:
                  - /
            tls:
              - secretName: vault-tls-certificate
                hosts:
                  - *host
          dataStorage:
            enabled: true
            # Size of the PVC created
            size: 10Gi
            # Location where the PVC will be mounted.
            mountPath: "/vault/data"
            # Name of the storage class to use.  If null it will use the
            # configured default Storage Class.
            storageClass: "longhorn"
{{- end }}
