{{- if .Values.vault.init.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: init-vault
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccount: init-tools
      restartPolicy: Never
      containers:
        - name: script
          image: locmai/init-tools:0.0.1
          command:
            - python
            - -c
          args:
            - |
{{ .Files.Get "files/vault_init.py" | indent 14 }}
{{- end }}
