apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: ''
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - git@github.com:locmai/**
  - https://github.com/locmai/**
  - https://grafana.github.io/helm-charts
  - https://prometheus-community.github.io/helm-charts
  - https://kiwigrid.github.io
  - https://sonatype.github.io/helm3-charts/
  - https://charts.jetstack.io
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/syncPolicy/automated
  destination:
    name: in-cluster
    namespace: platform
  source:
    path: 'platform/argocd'
    repoURL: git@github.com:locmai/humble.git
    targetRevision: main
    helm:
      values: |
        argocd:
          targetRevision: main