argocd:
  namespace: argocd
  project: platform
  targetRevision: main

# Kube Prometheus + Grafana stack 
monitoring:
  enabled: true
  namespace: monitoring

# Enable Grafana Dashboards app
dashboard:
  enabled: true
  namespace: monitoring
  targetRevision: main

loki:
  enabled: true
  namespace: monitoring

graphite:
  enabled: true

certManager:
  enabled: true
  installCRDs: true
  namespace: argocd
  targetRevision: v1.5.2
