argocd:
  namespace: argocd
  project: platform
  targetRevision: main

# Kube Prometheus + Grafana stack 
monitoring:
  enabled: true
  namespace: monitoring

# Enable Grafana Dashboards app
dashboard:
  enabled: true
  namespace: monitoring
  targetRevision: main

graphite:
  enabled: true

loki:
  enabled: true
  namespace: monitoring

certManager:
  enabled: true
  installCRDs: true
  namespace: argocd
  targetRevision: v1.5.2

tekton:
  enabled: true
  targetRevision: main
  namespace: tekton

kubeless:
  enabled: false
  targetRevision: main
  namespace: kubeless

sonarqube:
  enabled: false
  namespace: sonarqube