argocd:
  namespace: argocd
  project: platform
  targetRevision: main

# Kube Prometheus + Grafana stack 
monitoring:
  enabled: true
  namespace: monitoring

loki:
  enabled: true
  namespace: monitoring

graphite:
  enabled: true
