kind: Secret
apiVersion: v1
metadata:
  name: humble-example-secret 
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "secret/humble/data/demo"
type: Opaque
stringData:
  username: <username>
