apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: ''
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - git@github.com:locmai/humble.git
  - https://charts.bitnami.com/bitnami
  - https://locmai.github.io/blackping/
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/syncPolicy/automated
  destination:
    name: in-cluster
    namespace: apps
  source:
    path: 'apps'
    repoURL: git@github.com:locmai/humble.git
    targetRevision: main
    helm:
      values: |
        argocd:
          targetRevision: main