argocd:
  namespace: argocd
  project: apps
  targetRevision: main

global:
  domain: "placeholder.com"

filebrowser:
  enabled: false

saleor:
  enabled: false

dendrite:
  enabled: true

element:
  enabled: true
