argocd:
  namespace: argocd
  project: apps
  targetRevision: main
global:
  domain: placeholder.com
  env: prod
filebrowser:
  enabled: false
dendrite:
  enabled: false
element:
  enabled: false
memcached:
  enabled: false
cortex:
  enabled: false
  basicAuth:
    insecure: true
    secretName: cortex-humble-tenant
microservicesDemo:
  enabled: false
dashyLandscape:
  enabled: true
consul:
  enabled: false
nfs:
  enabled: false
yutaops:
  enabled: true

# GitOps
djangodemo:
  enabled: true
  deployments:
    main:
      subdomain: alvisio-test
      tag: 0.0.1
    release:
      subdomain: alvisio-release
      tag: 0.0.1
