filebrowser:
  enabled: false

dendrite:
  enabled: false
  storageClass: "longhorn"

element:
  enabled: false


# Playground services
memcached:
  enabled: false

cortex:
  enabled: false

microservicesDemo:
  enabled: false

dashyLandscape:
  enabled: true

consul:
  enabled: false

nfs:
  enabled: false

yutaops:
  enabled: true
