argocd:
  namespace: argocd
  project: apps
  targetRevision: main

global:
  domain: "placeholder.com"

filebrowser:
  enabled: false

saleor:
  enabled: false

dendrite:
  enabled: true

element:
  enabled: true

matrixalertmanager:
  enabled: false

# Playground services
memcached:
  enabled: true

cortex:
  enabled: false

microservicesDemo:
  enabled: true
