{{- if .Values.certmanager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-cert-manager
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.certmanager.namespace }}
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.6.1
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true

        prometheus:
          enabled: true
          # TODO enable when figuring out how to install Prometheus CRD first
          servicemonitor:
            enabled: false
{{- end }}
helm template cert-manager jetstack/cert-manager --namespace cert-manager --set prometheus.servicemonitor.enabled=true
