apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-grafana-test
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.monitoring.namespace }}
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.32.7
    helm:
      releaseName: grafanatest
      values: |
        grafana:
          replicas: 1
          enableServiceLinks: false
          env:
            JAEGER_AGENT_PORT: '5755'
            OIDC_CLIENT_ID: 'vault:humble/data/humble/boundary-oidc-client#client_id'
            OIDC_CLIENT_SECRET: 'vault:humble/data/boundary-oidc-client#client_secret'
