{{- if .Values.systemUpgrade.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-system-upgrade
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.systemUpgrade.namespace }}
  source:
    repoURL: {{ .Values.global.repoURL }}
    path: 'system/kustomization/system-upgrade'
    targetRevision: {{ .Values.systemUpgrade.targetRevision }}
{{- end }}
