{{- if .Values.longhorn.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-longhorn
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.longhorn.namespace }}
  source:
    chart: longhorn
    repoURL: 'https://github.com/longhorn/charts.git'
    path: "./charts/longhorn"
    targetRevision: master
    helm:
      releaseName: longhorn
      values: |
        persistence:
          defaultClassReplicaCount: 2
{{- end }}
