{{- if .Values.longhorn.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-longhorn
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.longhorn.namespace }}
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.2.2
    helm:
      releaseName: longhorn
      values: |
        ingress:
          enabled: true
          host: &host longhorn.maibaloc.com
          tlse: true
          tlsSecret: longhorn-tls-certificate
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
{{- end }}
