{{- if .Values.monitoring.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-monitoring
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.monitoring.namespace }}
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 13.7.2
    helm:
      releaseName: monitoring
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelector: {}
            podMonitorSelectorNilUsesHelmValues: false
            podMonitorNamespaceSelector: {}
            containers:
            - name: prometheus
              env:
              - name: JAEGER_AGENT_PORT
                value: "5755"
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 20Gi

          server:
            enableServiceLinks: false

        prometheusOperator:
          admissionWebhooks:
            enabled: false
            failurePolicy: Ignore
            patch:
              enabled: false
          tls:
            enabled: false
          denyNamespaces:
            - 'notreal'
        grafana:
          enabled: true
          enableServiceLinks: false
          env:
            JAEGER_AGENT_PORT: '5755'
          image:
            tag: 8.3.1
          persistence:
            enabled: false
          ingress:
            enabled: false
          sidecar:
            image:
              repository: omegavveapon/kopf-k8s-sidecar
              tag: 1.3.4
            dashboards:
              enabled: true
              label: grafana_dashboard
              folder: /tmp/dashboards
              searchNamespace: {{ .Values.monitoring.namespace }}
              provider:
                foldersFromFilesStructure: true
              annotations:
                k8s-sidecar-target-directory: "/tmp/dashboards/kubernetes"
          plugins:
          - yesoreyeram-boomtheme-panel
          - flant-statusmap-panel
          - vonage-status-panel
          - natel-discrete-panel
          - grafana-polystat-panel
          - digiapulssi-breadcrumb-panel
          - macropower-analytics-panel

        alertmanager:
          config:
            global:
              resolve_timeout: 5m
            route:
              group_by: ['job']
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 2h
              receiver: 'matrix'
              routes:
              - match:
                  alertname: Watchdog
                receiver: 'matrix'
            receivers:
            - name: 'matrix'
              webhook_configs:
                - url: 'http://neb.apps.svc.cluster.local/services/hooks/YWxlcnRtYW5hZ2VyX3NlcnZpY2U'
{{- end }}
