{{- if .Values.monitoring.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-monitoring
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.monitoring.namespace }}
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 37.0.0
    helm:
      releaseName: monitoring
      values: |
        prometheus:
          prometheusSpec:
            replicas: 1
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelector: {}
            podMonitorSelectorNilUsesHelmValues: false
            podMonitorNamespaceSelector: {}
            containers:
            - name: prometheus
              env:
              - name: JAEGER_AGENT_PORT
                value: "5755"
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 20Gi
            {{- if .Values.monitoring.remoteWrite.enabled }}
            remoteWrite:
              - url: http://cortex-nginx.apps:80/api/v1/push
                headers:
                  X-Scope-OrgID: humble
                basicAuth:
                  username:
                    name: cortex-humble-tenant
                    key: username
                  password:
                    name: cortex-humble-tenant
                    key: password
            {{- end }}
          server:
            enableServiceLinks: false

        prometheusOperator:
          admissionWebhooks:
            enabled: false
            failurePolicy: Ignore
            patch:
              enabled: false
          tls:
            enabled: false
          denyNamespaces:
            - 'notreal'
        grafana:
          enabled: true
          replicas: 1
          enableServiceLinks: false
          env:
            JAEGER_AGENT_PORT: '5755'
            OIDC_CLIENT_ID: 'vault:secret/data/humble/boundary-oidc-client#client_id'
            OIDC_CLIENT_SECRET: 'vault:secret/data/humble/boundary-oidc-client#client_secret'
          image:
            tag: 8.4.4
          persistence:
            enabled: false
          ingress:
            enabled: false
          podAnnotations:
            vault.security.banzaicloud.io/vault-addr: "https://vault.platform:8200"
            vault.security.banzaicloud.io/vault-role: "default"
            vault.security.banzaicloud.io/vault-path: "kubernetes"
            vault.maibaloc.com/oidc-reference.version: v0.1 # change this when the OIDC reference gets changed
          grafana.ini:
            auth.generic_oauth:
              name: Vault
              enabled: true
              allow_sign_up: false
              client_id: "vault:secret/data/humble/boundary-oidc-client#client_id"
              client_secret: "vault:secret/data/humble/boundary-oidc-client#client_secret"
              scopes: openid groups user email
              auth_url: "https://vault.maibaloc.com/ui/vault/identity/oidc/provider/vault-provider/authorize"
              token_url: "https://vault.maibaloc.com/v1/identity/oidc/provider/vault-provider/token"
              api_url: "https://vault.maibaloc.com/v1/identity/oidc/provider/vault-provider/userinfo"
          sidecar:
            image:
              repository: omegavveapon/kopf-k8s-sidecar
              tag: 1.3.4
            dashboards:
              enabled: true
              label: grafana_dashboard
              folder: /tmp/dashboards
              searchNamespace: {{ .Values.monitoring.namespace }}
              provider:
                foldersFromFilesStructure: true
              annotations:
                k8s-sidecar-target-directory: "/tmp/dashboards/kubernetes"
          additionalDataSources:
            - name: loki
              type: loki
              editable: false
              url: http://loki-stack:3100
              isDefault: false
          plugins:
          - yesoreyeram-boomtheme-panel
          - flant-statusmap-panel
          - vonage-status-panel
          - natel-discrete-panel
          - grafana-polystat-panel
          - digiapulssi-breadcrumb-panel
          - macropower-analytics-panel

        alertmanager:
          enabled: true
          config:
            global:
              resolve_timeout: 5m
            route:
              group_by: ['alertname', 'job', 'ops']
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 2h
              receiver: "yutaops-webhook"
              routes:
              - match:
                  ops: yuta
                receiver: 'yutaops-webhook'
              - match:
                  ops: argo-events
                receiver: 'argo-eventsource'
            receivers:
            - name: 'yutaops-webhook'
              webhook_configs:
                - url: 'http://yutaops-webhook.apps.svc.cluster.local:8501/webhook'
            - name: 'argo-eventsource'
              webhook_configs:
                - url: 'http://webhook-demo-eventsource-svc.argoworkflow.svc.cluster.local:12000/demo'
{{- end }}
