{{- if .Values.monitoring.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-monitoring
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.monitoring.namespace }}
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 13.7.2
    helm:
      releaseName: monitoring
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelector: {}
        prometheusOperator:
          admissionWebhooks:
            enabled: true
            failurePolicy: Ignore
            patch:
              enabled: true
        grafana:
          enabled: true
          image:
            tag: 8.3.1
          persistence:
            enabled: false
          ingress:
            enabled: false
          sidecar:
            image:
              repository: omegavveapon/kopf-k8s-sidecar
              tag: 1.3.4
            dashboards:
              enabled: true
              label: grafana_dashboard
              folder: /tmp/dashboards
              searchNamespace: monitoring
              provider:
                foldersFromFilesStructure: true
              annotations:
                k8s-sidecar-target-directory: "/tmp/dashboards/kubernetes"
          plugins:
          - yesoreyeram-boomtheme-panel
          - flant-statusmap-panel
          - vonage-status-panel
          - natel-discrete-panel
          - grafana-polystat-panel
          - digiapulssi-breadcrumb-panel
          - macropower-analytics-panel
{{- end }}
