# app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: apps
  labels:
    app: vault-agent-demo
spec:
  selector:
    matchLabels:
      app: vault-agent-demo
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-config: 'secret/postgresql/data'
        vault.hashicorp.com/role: "postgresql_read_only"
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "secret/postgresql/data" -}}
            export DSN="postgres://{{ .Data.data.kratos_username }}:{{ .Data.data.kratos_password }}@postgresql:5432/{{ .Data.data.kratos_database }}?sslmode=disable&max_conns=20&max_idle_conns=4"
          {{- end }}
      labels:
        app: vault-agent-demo
    spec:
      serviceAccountName: postgresql
      containers:
      - name: app
        image: alpine:latest
        args:
          ['sh', '-c', 'source /vault/secrets/config && env']
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  namespace: apps
  labels:
    app: vault-agent-demo