---
- include_tasks: variables.yaml

- name: Print all available facts
  ansible.builtin.debug:
    var: initial_cluster_string

- name: Create etcd-data directory
  ansible.builtin.file:
    path: /var/lib/genesis/etcd
    state: directory
    mode: '0644'

- name: Initialize etcd
  docker_container:
    name: 'etcd-{{ ansible_nodename }}'
    image: 'quay.io/coreos/etcd:v3.4.15'
    restart_policy: unless-stopped
    volumes:
    - /usr/share/ca-certificates/:/etc/ssl/certs
    - /var/lib/genesis/etcd:/etcd-data
    ports:
    - "2480:2480"
    - "2479:2479"
    - "5001:5001"
    command:
    - /usr/local/bin/etcd
    - --name etcd-{{ ansible_nodename }}
    - --data-dir=/etcd-data
    - --advertise-client-urls "http://{{ ansible_default_ipv4.address }}:2479,http://{{ ansible_default_ipv4.address }}:5001"
    - --listen-client-urls "http://0.0.0.0:2479,http://0.0.0.0:5001"
    - --initial-advertise-peer-urls "http://{{ ansible_default_ipv4.address }}:2480"
    - --listen-peer-urls "http://0.0.0.0:2480"
    - --initial-cluster-token etcd-genesis-cluster
    - --initial-cluster {{ initial_cluster_string }}
    - --initial-cluster-state new
