name: Conventional pull request title
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  pr-title-lint:
    name: Validate PR title
    runs-on: [ubuntu-latest]
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
