name: Release Please
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          bump-minor-pre-major: true
          token: ${{ secrets.CI_TOKEN }}
          bootstrap-sha: c9c135a663bb7c6e4b835ba2f315b71f396d4117
