name: Renovate
on:
  schedule:
    # For everyday at 11PM
    - cron: '0 23 * * *'
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.13.2
        with:
          configurationFile: renovate.json5
          token: ${{ secrets.CI_TOKEN }}
