{{- if .Values.ory_kratos.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-ory-kratos
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.argocd.project }}
  source:
    chart: kratos
    repoURL: https://locmai.github.io/ory-k8s/
    targetRevision: {{ .Values.ory_kratos.targetRevision }}
    helm:
      releaseName: ory-kratos
      values: |
        kratos:
          development: true
          # autoMigrate is relying on a simple initContainer mechanism
          # Do not turn it on if the replicaCount > 1
          autoMigrate: false
          
          config:
            selfservice:
              methods:
                password:
                  enabled: false
                oidc:
                  enabled: false
              default_browser_return_url: "https://localhostofnothing.com"
            courier:
              smtp:
                connection_uri: "smtp://whatever.com"
            identity: 
              default_schema_url: "https://raw.githubusercontent.com/locmai/humble/main/apps/argocd/apps/identity.schema.json"
        serviceAccount:
          enabled: true
          name: "postgresql"
        deployment:
          command: ["/bin/sh"]
          args:
            - "-c"
            - ". /vault/secrets/config && kratos serve all --config /etc/config/kratos.yaml"

          extraEnv:
            - name: LOG_LEVEL
              value: "trace"
          annotations:
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-inject-secret-config: 'secret/postgresql/data'
            vault.hashicorp.com/role: "postgresql_read_only"
            vault.hashicorp.com/agent-inject-template-config: |
              {{`{{ with secret "secret/postgresql/data" -}}
                export DSN="postgres://{{ .Data.data.kratos_username }}:{{ .Data.data.kratos_password }}@postgresql:5432/{{ .Data.data.kratos_database }}?sslmode=disable&max_conns=20&max_idle_conns=4"
              {{- end }}`}}
{{- end }}
