{{- if .Values.ory_kratos.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-ory-kratos
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.argocd.project }}
  source:
    chart: kratos
    repoURL: https://locmai.github.io/ory-k8s/
    targetRevision: {{ .Values.ory_kratos.targetRevision }}
    helm:
      releaseName: ory-kratos
      values: |
        kratos:
          development: true
          # autoMigrate is relying on a simple initContainer mechanism
          # Do not turn it on if the replicaCount > 1
          autoMigrate: false
          
          config:
            selfservice:
              methods:
                password:
                  enabled: false
                oidc:
                  enabled: false
              default_browser_return_url: "https://localhostofnothing.com"
            courier:
              smtp:
                connection_uri: "smtp://whatever.com"
            identitySchemas:
              "identity.default.schema.json": |
                {
                  "$id": "https://example.com/registration.schema.json",
                  "$schema": "http://json-schema.org/draft-07/schema#",
                  "title": "User",
                  "type": "object",
                  "properties": {
                    "traits": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string",
                          "ory.sh/kratos": {
                            "credentials": {
                              "password": {
                                "identifier": true
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
        serviceAccount:
          enabled: true
          name: "postgresql"
        deployment:
          annotations:
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-inject-secret-postgresql: 'secret/postgresql/data'
            vault.hashicorp.com/role: "postgresql_read_only"
            vault.hashicorp.com/agent-inject-template-postgresql: |
              {{`{{ with secret "secret/postgresql/data" -}}
                export DSN="postgres://{{ .Data.kratos_username }}:{{ .Data.kratos_password }}@postgresql:5432/{{ .Data.kratos_database }}?sslmode=disable&max_conns=20&max_idle_conns=4"
              {{- end }}`}}
{{- end }}
