{{- if .Values.postgresql.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-postgresql
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  destination:
    name: in-cluster
    namespace: {{ .Values.argocd.project }}
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.6.4
    helm:
      releaseName: postgresql
      values: |
        commonAnnotations:
          vault.hashicorp.com/agent-inject: "true"
          vault.hashicorp.com/agent-inject-secret-postgresql: "secrets/postgresql"
          vault.hashicorp.com/role: "postgresql_read_only"
          vault.hashicorp.com/agent-inject-template-postgresql: |
            {{ with secret "secrets/postgresql" -}}
              export POSTGRES_PASSWORD="{{ .Data.data.password }}"
            {{- end }}
        serviceAccount:
          enabled: true
{{- end }}
